browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: edge
    version: latest
  - name: and_chr
    version: latest
  - name: ios_saf
    version: latest
providers:
  - airtap-system
presets:
  local:
    providers: airtap-manual
    browsers:
      - name: manual
browserify:
  - transform: babelify
    global: true
    presets: ['@babel/preset-env']